[package]
name = "sqllogs-gen"
version = "0.2.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.38"
lazy_static = "1.5.0"
rand = "0.8.5"
regex = "1.11.1"
